global using VocaNova.API.Features.SuperAdmin.BLL.Services.IServices;
global using VocaNova.API.Features.Admin.BLL.Services.IServices;
global using VocaNova.API.Common.Abstractions.Configuration;
global using VocaNova.API.Common.Abstractions.Transactions;
global using VocaNova.API.Common.Models;
global using VocaNova.API.Features.AiGrading.BLL.Abstractions;
global using VocaNova.API.Features.AiGrading.BLL.Models;
global using VocaNova.API.Features.AiGrading.BLL.Services;
global using VocaNova.API.Features.AiGrading.BLL.Services.IServices;
global using VocaNova.API.Features.AiGrading.Contracts.Requests;
global using VocaNova.API.Features.AiGrading.Contracts.Responses;
global using VocaNova.API.Features.AiGrading.Controllers;
global using VocaNova.API.Features.AiGrading.DAL.Repositories;
global using VocaNova.API.Features.AiGrading.Mappings;
global using VocaNova.API.Features.Auth.BLL.Abstractions;
global using VocaNova.API.Features.Auth.BLL.Models;
global using VocaNova.API.Features.Auth.BLL.Services;
global using VocaNova.API.Features.Auth.BLL.Services.IServices;
global using VocaNova.API.Features.Auth.Contracts.Requests;
global using VocaNova.API.Features.Auth.Contracts.Responses;
global using VocaNova.API.Features.Auth.DAL.Repositories;
global using VocaNova.API.Features.Auth.Mappings;
global using VocaNova.API.Features.Dictionary.BLL.Abstractions;
global using VocaNova.API.Features.Dictionary.BLL.Models;
global using VocaNova.API.Features.Dictionary.BLL.Services;
global using VocaNova.API.Features.Dictionary.BLL.Services.IServices;
global using VocaNova.API.Features.Dictionary.Contracts.Requests;
global using VocaNova.API.Features.Dictionary.Contracts.Responses;
global using VocaNova.API.Features.Dictionary.Controllers;
global using VocaNova.API.Features.Dictionary.DAL.Repositories;
global using VocaNova.API.Features.Dictionary.Mappings;
global using VocaNova.API.Features.Knn.BLL.Abstractions;
global using VocaNova.API.Features.Knn.BLL.Models;
global using VocaNova.API.Features.Knn.BLL.Services;
global using VocaNova.API.Features.Knn.BLL.Services.IServices;
global using VocaNova.API.Features.Knn.Contracts.Requests;
global using VocaNova.API.Features.Knn.Contracts.Responses;
global using VocaNova.API.Features.Knn.Controllers;
global using VocaNova.API.Features.Knn.DAL.Repositories;
global using VocaNova.API.Features.Knn.Mappings;
global using VocaNova.API.Features.Lists.BLL.Abstractions;
global using VocaNova.API.Features.Lists.BLL.Models;
global using VocaNova.API.Features.Lists.BLL.Services;
global using VocaNova.API.Features.Lists.BLL.Services.IServices;
global using VocaNova.API.Features.Lists.Contracts.Requests;
global using VocaNova.API.Features.Lists.Contracts.Responses;
global using VocaNova.API.Features.Lists.DAL.Repositories;
global using VocaNova.API.Features.Lists.Mappings;
global using VocaNova.API.Features.Notifications.BLL.Abstractions;
global using VocaNova.API.Features.Notifications.BLL.Models;
global using VocaNova.API.Features.Notifications.BLL.Services;
global using VocaNova.API.Features.Notifications.BLL.Services.IServices;
global using VocaNova.API.Features.Notifications.Contracts.Requests;
global using VocaNova.API.Features.Notifications.Controllers;
global using VocaNova.API.Features.Notifications.DAL.Repositories;
global using VocaNova.API.Features.Progress.BLL.Abstractions;
global using VocaNova.API.Features.Progress.BLL.Models;
global using VocaNova.API.Features.Progress.BLL.Services;
global using VocaNova.API.Features.Progress.BLL.Services.IServices;
global using VocaNova.API.Features.Progress.Contracts.Requests;
global using VocaNova.API.Features.Progress.Contracts.Responses;
global using VocaNova.API.Features.Progress.Controllers;
global using VocaNova.API.Features.Progress.DAL.Repositories;
global using VocaNova.API.Features.Quiz.BLL.Abstractions;
global using VocaNova.API.Features.Quiz.BLL.Models;
global using VocaNova.API.Features.Quiz.BLL.Services;
global using VocaNova.API.Features.Quiz.BLL.Services.IServices;
global using VocaNova.API.Features.Quiz.Contracts.Requests;
global using VocaNova.API.Features.Quiz.Contracts.Responses;
global using VocaNova.API.Features.Quiz.Controllers;
global using VocaNova.API.Features.Quiz.DAL.Repositories;
global using VocaNova.API.Features.Quiz.Mappings;
global using VocaNova.API.Infrastructure.Caching;
global using VocaNova.API.Infrastructure.Caching.Dictionary;
global using VocaNova.API.Infrastructure.Caching.Knn;
global using VocaNova.API.Infrastructure.Caching.Lists;
global using VocaNova.API.Infrastructure.Caching.Progress;
global using VocaNova.API.Infrastructure.Caching.Quiz;
global using VocaNova.API.Infrastructure.Authentication;
global using VocaNova.API.Infrastructure.Caching.Auth;
global using VocaNova.API.Infrastructure.ExternalServices.Gemini;
global using VocaNova.API.Infrastructure.HostedServices;
global using VocaNova.API.Infrastructure.Otp;
global using VocaNova.API.Infrastructure.Persistence;
global using VocaNova.API.Infrastructure.Persistence.Transactions;
global using VocaNova.API.Infrastructure.RateLimiting;
global using VocaNova.API.Infrastructure.Sms;
global using VocaNova.API.Infrastructure.Storage;
global using VocaNova.API.Infrastructure.Configuration;

global using AiGradingConfigService = VocaNova.API.Features.AiGrading.BLL.Services.AiGradingConfigurationService;
global using AiGradingResult = VocaNova.API.Features.AiGrading.BLL.Models.AiGrade;
global using AiGradingSettings = VocaNova.API.Features.AiGrading.BLL.Models.AiGradingConfiguration;
global using AuthRateLimitSettings = VocaNova.API.Features.Auth.BLL.Models.AuthRateLimitOptions;
global using EntityUserProfile = VocaNova.API.Infrastructure.Persistence.Entities.UserProfile;
global using EntityUserWordProgress = VocaNova.API.Infrastructure.Persistence.Entities.UserWordProgress;
global using EntityWord = VocaNova.API.Infrastructure.Persistence.Entities.Word;
global using EntityWordDerivedForm = VocaNova.API.Infrastructure.Persistence.Entities.WordDerivedForm;
global using EntityWordExample = VocaNova.API.Infrastructure.Persistence.Entities.WordExample;
global using EntityWordIdiom = VocaNova.API.Infrastructure.Persistence.Entities.WordIdiom;
global using EntityWordRelation = VocaNova.API.Infrastructure.Persistence.Entities.WordRelation;
global using EntityWordSense = VocaNova.API.Infrastructure.Persistence.Entities.WordSense;
global using EntityWordTopic = VocaNova.API.Infrastructure.Persistence.Entities.WordTopic;
global using BuildQuizPoolRequest = VocaNova.API.Features.Quiz.BLL.Models.BuildQuizPoolCommand;
global using CachedAiGradingResult = VocaNova.API.Features.AiGrading.BLL.Models.CachedAiGrade;
global using GoogleUserInfo = VocaNova.API.Features.Auth.BLL.Models.GoogleIdentity;
global using IGoogleTokenVerifier = VocaNova.API.Features.Auth.BLL.Abstractions.IGoogleIdentityProvider;
global using IAudioStorage = VocaNova.API.Features.Dictionary.BLL.Abstractions.IWordAudioStorage;
global using IKnnRuntimeConfigService = VocaNova.API.Features.Knn.BLL.Services.IServices.IKnnRuntimeConfigurationService;
global using ISmsProvider = VocaNova.API.Features.Auth.BLL.Abstractions.ISmsSender;
global using KnnRuntimeConfigService = VocaNova.API.Features.Knn.BLL.Services.KnnRuntimeConfigurationService;
global using KnnConfigDto = VocaNova.API.Features.Knn.Contracts.Responses.KnnConfigResponse;
global using KnnMathHelper = VocaNova.API.Features.Knn.BLL.Services.KnnMath;
global using KnnVectorWeightsDto = VocaNova.API.Features.Knn.BLL.Models.KnnVectorWeights;
global using OtpSendResult = VocaNova.API.Features.Auth.BLL.Models.OtpSendResult;
global using ProgressSummaryDto = VocaNova.API.Features.Progress.BLL.Models.ProgressSummary;
global using QuizSubmitRepository = VocaNova.API.Features.Quiz.DAL.Repositories.QuizSubmissionRepository;
global using QuizWordPoolRepository = VocaNova.API.Features.Quiz.DAL.Repositories.QuizPoolRepository;
global using QuizSubmitService = VocaNova.API.Features.Quiz.BLL.Services.QuizSubmissionService;
global using QuizPoolWordDto = VocaNova.API.Features.Quiz.BLL.Models.QuizPoolWord;
global using TopicRecommendationDto = VocaNova.API.Features.Knn.BLL.Models.TopicRecommendation;
global using TopicSummaryDto = VocaNova.API.Features.Dictionary.BLL.Models.TopicSummary;
global using UserListDto = VocaNova.API.Features.Lists.BLL.Models.UserListSummary;
global using UserProfileDto = VocaNova.API.Features.Auth.BLL.Models.UserProfile;
global using WordDetailDto = VocaNova.API.Features.Dictionary.BLL.Models.WordDetail;
global using WordAudioDto = VocaNova.API.Features.Dictionary.BLL.Models.WordAudio;
global using WordDerivedFormDto = VocaNova.API.Features.Dictionary.BLL.Models.WordDerivedForm;
global using WordExampleDto = VocaNova.API.Features.Dictionary.BLL.Models.WordExample;
global using WordIdiomDto = VocaNova.API.Features.Dictionary.BLL.Models.WordIdiom;
global using WordRelationDto = VocaNova.API.Features.Dictionary.BLL.Models.WordRelation;
global using WordSenseDto = VocaNova.API.Features.Dictionary.BLL.Models.WordSense;
global using WordTopicDto = VocaNova.API.Features.Dictionary.BLL.Models.WordTopic;
global using WordSummaryDto = VocaNova.API.Features.Dictionary.BLL.Models.WordSummary;
